// Mock UI data for CompareHub frontend

export const MOCK_PRODUCTS = [
  {
    id: 'prod-1',
    title: 'Apple iPhone 15 Pro (128 GB) - Natural Titanium',
    category: 'Smartphones',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 3420,
    cheapestPrice: 127990,
    originalPrice: 134900,
    isCheapest: true,
    isBestValue: true,
    priceHistory: [
      { month: 'Apr', price: 134900 },
      { month: 'May', price: 132500 },
      { month: 'Jun', price: 131900 },
      { month: 'Jul', price: 129990 },
      { month: 'Aug', price: 127990 },
    ],
    lowest30DaysPrice: 127990,
    merchantOffers: [
      {
        id: 'mo-1-1',
        merchantName: 'Amazon',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
        price: 127990,
        originalPrice: 134900,
        deliveryTime: 'Free Next-Day Delivery',
        inStock: true,
        isCheapest: true,
        rating: 4.9,
        offerTag: '₹7,000 Bank Discount',
        productUrl: '#',
      },
      {
        id: 'mo-1-2',
        merchantName: 'Flipkart',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Flipkart_logo.svg',
        price: 128990,
        originalPrice: 134900,
        deliveryTime: 'Delivery in 2 Days',
        inStock: true,
        isCheapest: false,
        rating: 4.7,
        offerTag: 'Extra ₹5,000 Off on Exchange',
        productUrl: '#',
      },
      {
        id: 'mo-1-3',
        merchantName: 'Croma',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Croma_Logo.svg',
        price: 129900,
        originalPrice: 134900,
        deliveryTime: 'Store Pickup Available Today',
        inStock: true,
        isCheapest: false,
        rating: 4.6,
        offerTag: 'Flat 5% Cashback',
        productUrl: '#',
      },
      {
        id: 'mo-1-4',
        merchantName: 'Vijay Sales',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Vijay_Sales_logo.png',
        price: 130990,
        originalPrice: 134900,
        deliveryTime: 'Delivery in 3-4 Days',
        inStock: true,
        isCheapest: false,
        rating: 4.5,
        offerTag: 'Free Case Included',
        productUrl: '#',
      },
    ],
  },
  {
    id: 'prod-2',
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    category: 'Audio & Headphones',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 5210,
    cheapestPrice: 26990,
    originalPrice: 34990,
    isCheapest: true,
    isBestValue: true,
    priceHistory: [
      { month: 'Apr', price: 32990 },
      { month: 'May', price: 29990 },
      { month: 'Jun', price: 28990 },
      { month: 'Jul', price: 27490 },
      { month: 'Aug', price: 26990 },
    ],
    lowest30DaysPrice: 26990,
    merchantOffers: [
      {
        id: 'mo-2-1',
        merchantName: 'Flipkart',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Flipkart_logo.svg',
        price: 26990,
        originalPrice: 34990,
        deliveryTime: 'Express Delivery by Tomorrow',
        inStock: true,
        isCheapest: true,
        rating: 4.8,
        offerTag: '₹2,000 Instant Card Discount',
        productUrl: '#',
      },
      {
        id: 'mo-2-2',
        merchantName: 'Amazon',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
        price: 27990,
        originalPrice: 34990,
        deliveryTime: 'Free 2-Day Shipping',
        inStock: true,
        isCheapest: false,
        rating: 4.9,
        offerTag: 'No Cost EMI Available',
        productUrl: '#',
      },
      {
        id: 'mo-2-3',
        merchantName: 'Headphone Zone',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_audio_icon.svg/640px-Black_audio_icon.svg.png',
        price: 28499,
        originalPrice: 34990,
        deliveryTime: 'Free Shipping in 3 Days',
        inStock: true,
        isCheapest: false,
        rating: 4.9,
        offerTag: 'Official Sony 2-Yr Warranty',
        productUrl: '#',
      },
    ],
  },
  {
    id: 'prod-3',
    title: 'MacBook Air 15-inch M3 Chip (16GB Unified Memory, 512GB SSD)',
    category: 'Laptops & Computers',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 1890,
    cheapestPrice: 144900,
    originalPrice: 154900,
    isCheapest: true,
    isBestValue: false,
    priceHistory: [
      { month: 'Apr', price: 154900 },
      { month: 'May', price: 151900 },
      { month: 'Jun', price: 148900 },
      { month: 'Jul', price: 146900 },
      { month: 'Aug', price: 144900 },
    ],
    lowest30DaysPrice: 144900,
    merchantOffers: [
      {
        id: 'mo-3-1',
        merchantName: 'Amazon',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
        price: 144900,
        originalPrice: 154900,
        deliveryTime: 'Free Delivery Tomorrow',
        inStock: true,
        isCheapest: true,
        rating: 4.9,
        offerTag: '₹10,000 Instant Savings',
        productUrl: '#',
      },
      {
        id: 'mo-3-2',
        merchantName: 'Reliance Digital',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Reliance_Digital_Logo.svg/1200px-Reliance_Digital_Logo.svg.png',
        price: 146900,
        originalPrice: 154900,
        deliveryTime: 'Same Day Store Pickup',
        inStock: true,
        isCheapest: false,
        rating: 4.7,
        offerTag: 'Free Laptop Backpack',
        productUrl: '#',
      },
      {
        id: 'mo-3-3',
        merchantName: 'Apple Store Online',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
        price: 154900,
        originalPrice: 154900,
        deliveryTime: 'Free Shipping',
        inStock: true,
        isCheapest: false,
        rating: 5.0,
        offerTag: 'Free Custom Engraving',
        productUrl: '#',
      },
    ],
  },
  {
    id: 'prod-4',
    title: 'Samsung Galaxy S24 Ultra 5G (12GB RAM, 256GB Titanium Gray)',
    category: 'Smartphones',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 2950,
    cheapestPrice: 119999,
    originalPrice: 129999,
    isCheapest: true,
    isBestValue: true,
    priceHistory: [
      { month: 'Apr', price: 129999 },
      { month: 'May', price: 126999 },
      { month: 'Jun', price: 124999 },
      { month: 'Jul', price: 122999 },
      { month: 'Aug', price: 119999 },
    ],
    lowest30DaysPrice: 119999,
    merchantOffers: [
      {
        id: 'mo-4-1',
        merchantName: 'Flipkart',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Flipkart_logo.svg',
        price: 119999,
        originalPrice: 129999,
        deliveryTime: 'Delivery in 2 Days',
        inStock: true,
        isCheapest: true,
        rating: 4.8,
        offerTag: '₹8,000 HDFC Instant Discount',
        productUrl: '#',
      },
      {
        id: 'mo-4-2',
        merchantName: 'Amazon',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
        price: 121999,
        originalPrice: 129999,
        deliveryTime: 'Free Next-Day Delivery',
        inStock: true,
        isCheapest: false,
        rating: 4.9,
        offerTag: 'Galaxy Watch 6 Bundle Offer',
        productUrl: '#',
      },
      {
        id: 'mo-4-3',
        merchantName: 'Samsung Official',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg',
        price: 124999,
        originalPrice: 129999,
        deliveryTime: 'Official Store Delivery',
        inStock: true,
        isCheapest: false,
        rating: 4.9,
        offerTag: 'Corporate Employee Discount',
        productUrl: '#',
      },
    ],
  },
  {
    id: 'prod-5',
    title: 'Sony PlayStation 5 Slim Console (Digital Edition)',
    category: 'Gaming & Consoles',
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 4620,
    cheapestPrice: 42990,
    originalPrice: 44990,
    isCheapest: true,
    isBestValue: true,
    priceHistory: [
      { month: 'Apr', price: 44990 },
      { month: 'May', price: 44990 },
      { month: 'Jun', price: 43990 },
      { month: 'Jul', price: 43490 },
      { month: 'Aug', price: 42990 },
    ],
    lowest30DaysPrice: 42990,
    merchantOffers: [
      {
        id: 'mo-5-1',
        merchantName: 'Amazon',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
        price: 42990,
        originalPrice: 44990,
        deliveryTime: 'Free Delivery in 2 Days',
        inStock: true,
        isCheapest: true,
        rating: 4.9,
        offerTag: '₹2,000 Coupon Applied',
        productUrl: '#',
      },
      {
        id: 'mo-5-2',
        merchantName: 'ShopAtSC (Sony Center)',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Sony_logo.svg/640px-Sony_logo.svg.png',
        price: 44990,
        originalPrice: 44990,
        deliveryTime: 'Store Delivery',
        inStock: true,
        isCheapest: false,
        rating: 4.8,
        offerTag: 'Extra DualSense Controller at 20% Off',
        productUrl: '#',
      },
    ],
  },
  {
    id: 'prod-6',
    title: 'Apple Watch Series 9 GPS 45mm Midnight Aluminum Case',
    category: 'Smart Watches & Wearables',
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 2180,
    cheapestPrice: 38990,
    originalPrice: 44900,
    isCheapest: true,
    isBestValue: true,
    priceHistory: [
      { month: 'Apr', price: 44900 },
      { month: 'May', price: 42900 },
      { month: 'Jun', price: 41490 },
      { month: 'Jul', price: 39990 },
      { month: 'Aug', price: 38990 },
    ],
    lowest30DaysPrice: 38990,
    merchantOffers: [
      {
        id: 'mo-6-1',
        merchantName: 'Croma',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Croma_Logo.svg',
        price: 38990,
        originalPrice: 44900,
        deliveryTime: 'Pick up in store in 2 hours',
        inStock: true,
        isCheapest: true,
        rating: 4.7,
        offerTag: '₹3,000 Instant Card Cashback',
        productUrl: '#',
      },
      {
        id: 'mo-6-2',
        merchantName: 'Amazon',
        merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
        price: 39990,
        originalPrice: 44900,
        deliveryTime: 'Free Next-Day Delivery',
        inStock: true,
        isCheapest: false,
        rating: 4.8,
        offerTag: 'No Cost EMI',
        productUrl: '#',
      },
    ],
  },
];

export const MOCK_FLIGHTS = [
  {
    id: 'fl-1',
    airline: 'IndiGo',
    airlineCode: '6E-2134',
    airlineLogo: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=100&auto=format&fit=crop&q=80',
    from: 'DEL',
    fromCity: 'New Delhi (DEL)',
    to: 'BOM',
    toCity: 'Mumbai (BOM)',
    departureTime: '06:00 AM',
    arrivalTime: '08:15 AM',
    duration: '2h 15m',
    stops: 0,
    stopDetails: 'Non-stop',
    price: 4280,
    originalPrice: 5199,
    cabinClass: 'Economy',
    aircraft: 'Airbus A321neo',
    seatsLeft: 4,
    isCheapest: true,
    isFastest: true,
    isBestValue: true,
    baggage: '7 kg Cabin • 15 kg Check-in',
    dealProvider: 'IndiGo Direct',
  },
  {
    id: 'fl-2',
    airline: 'Air India',
    airlineCode: 'AI-805',
    airlineLogo: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=100&auto=format&fit=crop&q=80',
    from: 'DEL',
    fromCity: 'New Delhi (DEL)',
    to: 'BOM',
    toCity: 'Mumbai (BOM)',
    departureTime: '09:30 AM',
    arrivalTime: '11:50 AM',
    duration: '2h 20m',
    stops: 0,
    stopDetails: 'Non-stop',
    price: 4690,
    originalPrice: 5800,
    cabinClass: 'Economy',
    aircraft: 'Boeing 777-300ER',
    seatsLeft: 7,
    isCheapest: false,
    isFastest: false,
    isBestValue: true,
    baggage: '7 kg Cabin • 20 kg Check-in + Free Meal',
    dealProvider: 'MakeMyTrip',
  },
  {
    id: 'fl-3',
    airline: 'Vistara (Air India Group)',
    airlineCode: 'UK-995',
    airlineLogo: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=100&auto=format&fit=crop&q=80',
    from: 'DEL',
    fromCity: 'New Delhi (DEL)',
    to: 'BOM',
    toCity: 'Mumbai (BOM)',
    departureTime: '11:15 AM',
    arrivalTime: '01:30 PM',
    duration: '2h 15m',
    stops: 0,
    stopDetails: 'Non-stop',
    price: 4950,
    originalPrice: 6200,
    cabinClass: 'Economy',
    aircraft: 'Airbus A320neo',
    seatsLeft: 3,
    isCheapest: false,
    isFastest: true,
    isBestValue: false,
    baggage: '7 kg Cabin • 15 kg Check-in + Gourmet Meal',
    dealProvider: 'EaseMyTrip',
  },
  {
    id: 'fl-4',
    airline: 'Akasa Air',
    airlineCode: 'QP-1302',
    airlineLogo: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=100&auto=format&fit=crop&q=80',
    from: 'DEL',
    fromCity: 'New Delhi (DEL)',
    to: 'BOM',
    toCity: 'Mumbai (BOM)',
    departureTime: '04:45 PM',
    arrivalTime: '07:05 PM',
    duration: '2h 20m',
    stops: 0,
    stopDetails: 'Non-stop',
    price: 4350,
    originalPrice: 5300,
    cabinClass: 'Economy',
    aircraft: 'Boeing 737 MAX 8',
    seatsLeft: 9,
    isCheapest: false,
    isFastest: false,
    isBestValue: false,
    baggage: '7 kg Cabin • 15 kg Check-in',
    dealProvider: 'Akasa Direct',
  },
  {
    id: 'fl-5',
    airline: 'SpiceJet',
    airlineCode: 'SG-8169',
    airlineLogo: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=100&auto=format&fit=crop&q=80',
    from: 'DEL',
    fromCity: 'New Delhi (DEL)',
    to: 'BOM',
    toCity: 'Mumbai (BOM)',
    departureTime: '01:20 PM',
    arrivalTime: '05:40 PM',
    duration: '4h 20m',
    stops: 1,
    stopDetails: '1 Stop via JAI (1h layover)',
    price: 3990,
    originalPrice: 4900,
    cabinClass: 'Economy',
    aircraft: 'Boeing 737-800',
    seatsLeft: 2,
    isCheapest: true,
    isFastest: false,
    isBestValue: false,
    baggage: '7 kg Cabin • 15 kg Check-in',
    dealProvider: 'Cleartrip',
  },
];

export const MOCK_RIDES = [
  {
    id: 'ride-uber-go',
    provider: 'Uber',
    providerIcon: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png',
    serviceName: 'Uber Go',
    vehicleCategory: 'cab',
    capacity: 4,
    description: 'Affordable, compact rides for daily commuting',
    etaMinutes: 3,
    distanceKm: 12.4,
    durationText: '24 mins',
    price: 249,
    originalPrice: 280,
    isCheapest: true,
    isBestValue: true,
    surgeMultiplier: 1.0,
    rating: 4.8,
  },
  {
    id: 'ride-ola-mini',
    provider: 'Ola',
    providerIcon: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Ola_Cabs_logo.png',
    serviceName: 'Ola Mini',
    vehicleCategory: 'cab',
    capacity: 4,
    description: 'Everyday comfortable hatchback rides',
    etaMinutes: 5,
    distanceKm: 12.4,
    durationText: '26 mins',
    price: 265,
    originalPrice: 295,
    isCheapest: false,
    isBestValue: false,
    surgeMultiplier: 1.1,
    rating: 4.6,
  },
  {
    id: 'ride-rapido-cab',
    provider: 'Rapido',
    providerIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rapido_Logo.png/800px-Rapido_Logo.png',
    serviceName: 'Rapido Cab',
    vehicleCategory: 'cab',
    capacity: 4,
    description: 'Guaranteed lowest cancellation rate cabs',
    etaMinutes: 4,
    distanceKm: 12.4,
    durationText: '25 mins',
    price: 252,
    originalPrice: 285,
    isCheapest: false,
    isBestValue: true,
    surgeMultiplier: 1.0,
    rating: 4.7,
  },
  {
    id: 'ride-uber-premier',
    provider: 'Uber',
    providerIcon: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png',
    serviceName: 'Uber Premier',
    vehicleCategory: 'cab',
    capacity: 4,
    description: 'Top-rated drivers in premium sedans',
    etaMinutes: 6,
    distanceKm: 12.4,
    durationText: '22 mins',
    price: 340,
    originalPrice: 380,
    isCheapest: false,
    isBestValue: false,
    surgeMultiplier: 1.0,
    rating: 4.9,
  },
  {
    id: 'ride-ola-auto',
    provider: 'Ola',
    providerIcon: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Ola_Cabs_logo.png',
    serviceName: 'Ola Auto',
    vehicleCategory: 'auto',
    capacity: 3,
    description: 'Doorstep auto pickup with zero haggling',
    etaMinutes: 2,
    distanceKm: 12.4,
    durationText: '30 mins',
    price: 165,
    originalPrice: 180,
    isCheapest: true,
    isBestValue: true,
    surgeMultiplier: 1.0,
    rating: 4.7,
  },
  {
    id: 'ride-rapido-auto',
    provider: 'Rapido',
    providerIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rapido_Logo.png/800px-Rapido_Logo.png',
    serviceName: 'Rapido Auto',
    vehicleCategory: 'auto',
    capacity: 3,
    description: 'Fast doorstep auto rickshaw rides',
    etaMinutes: 3,
    distanceKm: 12.4,
    durationText: '29 mins',
    price: 168,
    originalPrice: 185,
    isCheapest: false,
    isBestValue: false,
    surgeMultiplier: 1.0,
    rating: 4.6,
  },
  {
    id: 'ride-rapido-bike',
    provider: 'Rapido',
    providerIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rapido_Logo.png/800px-Rapido_Logo.png',
    serviceName: 'Rapido Bike',
    vehicleCategory: 'bike',
    capacity: 1,
    description: 'Beat the traffic on swift bike taxi',
    etaMinutes: 2,
    distanceKm: 12.4,
    durationText: '18 mins',
    price: 89,
    originalPrice: 110,
    isCheapest: true,
    isBestValue: true,
    surgeMultiplier: 1.0,
    rating: 4.8,
  },
  {
    id: 'ride-uber-moto',
    provider: 'Uber',
    providerIcon: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png',
    serviceName: 'Uber Moto',
    vehicleCategory: 'bike',
    capacity: 1,
    description: 'Affordable motorcycle ride through city jams',
    etaMinutes: 4,
    distanceKm: 12.4,
    durationText: '19 mins',
    price: 94,
    originalPrice: 115,
    isCheapest: false,
    isBestValue: false,
    surgeMultiplier: 1.0,
    rating: 4.7,
  },
];

export const MOCK_ALERTS = [
  {
    id: 'alert-1',
    type: 'product',
    title: 'Apple iPhone 15 Pro (128 GB)',
    targetPrice: 125000,
    currentPrice: 127990,
    initialPrice: 134900,
    createdAt: '2026-08-15',
    status: 'ACTIVE',
    channel: 'Email & Push',
  },
  {
    id: 'alert-2',
    type: 'flight',
    title: 'New Delhi (DEL) → Mumbai (BOM)',
    targetPrice: 4000,
    currentPrice: 4280,
    initialPrice: 5200,
    createdAt: '2026-08-20',
    status: 'TRIGGERED',
    channel: 'Email',
  },
];

export const MOCK_SAVED_ITEMS = [
  {
    id: 'saved-1',
    type: 'product',
    title: 'Sony WH-1000XM5 Wireless Headphones',
    price: 26990,
    badge: 'Cheapest on Flipkart',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    savedAt: '2 days ago',
  },
  {
    id: 'saved-2',
    type: 'flight',
    title: 'DEL → BOM (IndiGo 6E-2134)',
    price: 4280,
    badge: 'Non-stop • 2h 15m',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&auto=format&fit=crop&q=80',
    savedAt: '5 days ago',
  },
];
